### ISSUE TITLE
There is no way to retrieve the value of identity columns when using Insert(entity)

### ISSUE THREAD

**Issue by MoonStorm** [xin9le/DeclarativeSql#21]
I couldn't find a way to return the database generated values when using DeclarativeSql with Dapper.
Is there a way to achieve that?

Thanks.

**Comment by xin9le** [comment]
It's by-design. Generally, [ExecuteNonQuery](https://msdn.microsoft.com/en-us/library/system.data.idbcommand.executenonquery) method returns the number of rows affected when insert/update/delete. Dapper uses ExecuteNonQuery method its internal. If you wanna get identity value, you should generate it separately before insert/update/delete command execution.

Thank you for using this library!!
Best regards.

**Comment by MoonStorm** [comment]
I'm sorry but I don't understand. Your library exposes a `connection.Insert<TEntity>` extension method. How am I suppose to use it if I can't get back the primary keys associated with the entity by the database? That makes the method useless then.

**Comment by xin9le** [comment]
Thanks for your feedback. I apologize for answer above. I will try to improve!
