### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by RodH257** [xin9le/DeclarativeSql#24]
Hi, 

Is there any way to pass through a transaction to the Insert methods? I'd like to roll back a previous insert if the next one fails.

**Comment by xin9le** [comment]
I'm really sorry. Now I don't provide its feature...

This is a big mistake on my feature design. Since I'm aware of this problem, I am considering some big changes in the vNext.

**Comment by RodH257** [comment]
No need to apologise, I really like where this library is headed, it's looking great so far. I'm looking forward to seeing what you come up with in vNext! Let me know if there's anything I can do to help.
