### ISSUE TITLE
transaction/connectionのインターフェース不一致

### ISSUE THREAD

**Issue by AveMarina** [xin9le/DeclarativeSql#33]
IDbTransactionExtensionは、Dapperの提供するIDbConnectionへの機能をTransaction向けに拡張したものと認識しています。
このIDbTransactionExtensionにおいて、QueryAsyncメソッドなど一部をサポート外となっていますが、transactionを指定した上でQueryAsyncの代替となるような(queryを自作した上で、任意のModelを使用できる)方法はありますか？

**Comment by xin9le** [comment]
`IDbTransactionExtension` は、DeclarativeSql が `IDbConnection` 提供する `Select` / `Insert` / `Update` / `Delete` などの拡張機能を `IDbTransaction` に向けて適用したものです。なので、Dapper が提供しているものについては一切搭載していません。

とはいえ、Dapper が提供する `Query` / `Execute` などのメソッドを使えて困ることはないと考えられるため、それらも DeclarativeSql に取り込むようにします。
