### ISSUE TITLE
transaction.Updateが実行できない

### ISSUE THREAD

**Issue by shika358** [xin9le/DeclarativeSql#34]
バージョン：v0.2.0-rc3
環境：SQL Server2012

```
1. transaction.Update(person);
2. transaction.Update(person, x => x.Name == "名前");
3. transaction.Update(person, x => x.Name == "名前", x => x.Name); 
4. transaction.Update(person, x => x.Name == "名前",x => new {x.Name,x.SortNo}); 
```

1と3は実行可能ですが、2と4では例外が発生します。
引数に誤りがあればご指摘いただけますでしょうか。
ご確認お願いします。

**Comment by xin9le** [comment]
ご連絡ありがとうございます。
もしお手数でなければ、以下の情報を頂けませんでしょうか？
- 例外の型
- 例外メッセージ
- スタックトレース

よろしくお願い致します。

**Comment by xin9le** [comment]
`ExpandoObjectExtensions.Merge` の `properties` 引数が null になり `AurgumentNullException` が発生する感じですね。完全にデグレしてるので修正します...。

**Comment by shika358** [comment]
はい、そこです。
今度からは例外もお伝えします。
お手数ですがよろしくお願いします。
