### ISSUE TITLE
bulk insertの戻り値にAuto Incrementで自動採番されたidの配列か最初のidを返して欲しい。

### ISSUE THREAD

**Issue by hamu502** [xin9le/DeclarativeSql#38]
SQL Sever、MySQL、Oracleなど複数DB対応を検討しており、本ライブラで解決したいと考えております。
insert後にエンティティのid列に確定したid値を設定する利用方法を想定しており、InsertAndGetメソッドのbulk insert版をイメージしています。
ご検討頂ければ幸いです。

お忙しいとは思いますが、よろしくお願いいたします。

**Comment by xin9le** [comment]
ご要望ありがとうございます。

実装時に id を戻すことは検討はしていました。ですが非常に難しいというか、データベースごとの差を吸収しきれなかったので断念した記憶です。とはいえ、もう一度実現できないか考えてみたいと思います。

pull-request は常に受け付けていますので、もしよい実装があればお知らせください。
