### ISSUE TITLE
OrderByについて

### ISSUE THREAD

**Issue by shika358** [xin9le/DeclarativeSql#40]
SelectでOrderByができるようにご検討いただけないでしょうか｡

PrimitiveSql.CreateSelect<Person>(x => x.Id, x => x.Name);
connection.Select<Person>(x => x.Id, x => x.Name);    

のようなシンプルなクエリの場合､
以下のように

```
select
Id,
Name
from Person
order by
SortOrder
```

SortOrderなど任意の並び順を指定することが多いです｡
(あくまで私の利用の範囲ですが｡)
ご検討くださればと存じます｡

**Comment by xin9le** [comment]
ご意見ありがとうございます :smiley:
しかし以下の理由から OrderBy は基本的に実装しない方針をしています。
- メソッドの引数がより複雑になる
- asc / desc を両方サポートしつつ利便性の高いメソッドインターフェースを提供しづらい
- インメモリに持ってきた後に LINQ で処理する方が圧倒的に柔軟
- データベース側で実行するのと LINQ で実行するのでそこまで大きなパフォーマンス差が出るとは思えない

以上を超えるメリットを感じれば実装を検討しますが、何か理由はありますでしょうか？

**Comment by shika358** [comment]
ご確認ありがとうございます｡
仰るとおり､LINQの処理で十分な内容でした｡
パフォーマンスも8万件弱のデータでほぼ変わりませんでした｡
ご検討ありがとうございます､勉強になりました｡
