### ISSUE TITLE
Configure character for enclosing tables with reserved names

### ISSUE THREAD

**Issue by diegohoyos** [xin9le/DeclarativeSql#41]
I have a table called Procedure, this name is a reserved keyword in SqlServer.
It would be great if based on DBKind enclose table name, for example [] for SQLServer or allow configure in TableMappingInfo this rules.

**Comment by xin9le** [comment]
Thank you for your advice and very nice pull-request!
I will try to fix reserved name problem.

However, you can avoid reserved name problem using `TableAttribute` like following.
Could you try this?

``` cs
//--- class definition
[Table("[Procedure]", Schema = "dbo")]
class Procedure
{
    [Column("[Foo]")]
    public string Foo { get; set; }
}

//--- create select sql
var sql = PrimitiveSql.CreateSelect<Procedure>();

// select
//     [Foo] as Foo
// from dbo.[Procedure]
```

**Comment by diegohoyos** [comment]
Yes it works, but in my solution not apply because: 1. my model classes are in pcl assembly and I can't add reference to DeclarativeSql libraries and 2 I need to support Sql server, Oracle and mysql, [ ] apply only for sql server
