### ISSUE TITLE
特定のUpdateでエラーが発生する

### ISSUE THREAD

**Issue by shika358** [xin9le/DeclarativeSql#44]
表題の件ですが、ご確認をお願いできますでしょうか

```
public class Parent
{
    public long Id{get;set;}
    public string Name{get;set;} 
    [NotMapped]
    public IList<Child> Children{get;set;}
}

public class Child
{
    public long Id{get;set;}
    public string Name{get;set;} 
}

public void Method()
{
    var parent = new Parent {
        Id = 1,
        Name = "Parent",
        Children = new List<Child> {
            new Child{Name = "Child"}
        }
    };

    using (var connection = DbProvider.CreateConnection(DbKind.SqlServer, "ConnectionString"))
    {
        connection.Update(parent, x => x.Id == parent.Id);
    }    
}
```

上記のようなUpdateを発行した場合、クエリ発行でエラーになります

```
return this.Connection.Execute(builder.ToString(), param, this.Transaction, this.Timeout);
```

paramを確認すると、public IList<Child> Children{get;set;} の値も含まれているようです
NotMappedの属性をつけていますので、paramに含まれないの正しいように思うのですがいかがでしょうか
※[Forkした弊社の環境ではとりあえずNotMappedを除外しています](https://github.com/shika358/DeclarativeSql/commit/098fd3dfd967d54f9f9a2086d57bb488683a76ae)
エラーは以下になります

Error
オブジェクトの型 Namespace.Models.ModelName から既知のマネージ プロバイダーのネイティブ型へのマップがありません。

StackTrace
   場所 System.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   場所 System.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
   場所 System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   場所 System.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters, Boolean includeReturnValue)
   場所 System.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   場所 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   場所 System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   場所 System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   場所 Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) 場所 D:\Dev\dapper-dot-net\Dapper NET40\SqlMapper.cs:行 3397
   場所 Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) 場所 D:\Dev\dapper-dot-net\Dapper NET40\SqlMapper.cs:行 1346
   場所 Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) 場所 D:\Dev\dapper-dot-net\Dapper NET40\SqlMapper.cs:行 1221
   場所 DeclarativeSql.Dapper.DbOperation.Update[T](T data, Expression`1 predicate, Expression`1 properties, Boolean setIdentity) 場所 C:\Data\Program\**\Applications\DeclarativeSql\Source\DeclarativeSql.Dapper\DbOperation.cs:行 460
   場所 DeclarativeSql.Dapper.IDbTransactionExtensions.Update[T](IDbTransaction transaction, T data, Expression`1 predicate, Expression`1 properties, Nullable`1 timeout, Boolean setIdentity) 場所 C:\Data\Program*_\Applications\DeclarativeSql\Source\DeclarativeSql.Dapper\IDbTransactionExtensions.cs:行 291
   場所 ConsoleApplication1.Program.Main(String[] args) 場所 C:\Data\Program\_*\Applications\DeclarativeSql\ConsoleApplication1\Program.cs:行 33
   場所 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   場所 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   場所 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   場所 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   場所 System.Threading.ThreadHelper.ThreadStart()

**Comment by xin9le** [comment]
ご報告ありがとうございます！
完全にバグなので修正します。

**Comment by xin9le** [comment]
修正して v0.2.3 をリリースしましたので、一旦 issue を閉じました。
もしミスがあれば、再度ご指摘のほどよろしくお願い致します。

**Comment by shika358** [comment]
迅速な対応ありがとうございます！
