### ISSUE TITLE
SQLServerのバルクインサートができなくなりました

### ISSUE THREAD

**Issue by dndmfx** [xin9le/DeclarativeSql#50]
・状況
SQL Serverのバルクインサートが、バージョン0.2.4までは成功していましたが、
0.2.5にアップデートしてから失敗するようになりました。

・環境
Visual Studio 2013
.Net Framework 4.5.2
SQLServer 2012 Express LocalDB

・詳細
以下のソースを実行すると例外が発生します。

namespace DeclarativeSqlTest
{
    public class Test
    {
        public Int32 Id { get; set; }
        public String Name { get; set; }
    }

    class Program
    {
        static void Main( string[] args )
        {
            using ( IDbConnection connection = DbProvider.CreateConnection( DbKind.SqlServer, @"ConnectionString" ) )
            {
                connection.Open();

                connection.BulkInsert( new[]
                {
                     new Test { Id = 1, Name = "AAA" },
                     new Test { Id = 2, Name = "BBB" },
                     new Test { Id = 3, Name = "CCC" },
                } );

                connection.Close();
            }
        }
    }
}

System.ArgumentException はハンドルされませんでした。
  HResult=-2147024809
  Message=列には有効な DataType が必要です。
  Source=System.Data
  StackTrace:
       場所 System.Data.DataColumn.set_DataType(Type value)
       場所 DeclarativeSql.Dapper.SqlServerOperation.SetupBulkInsert[T](SqlBulkCopy executor, IEnumerable`1 data)
       場所 DeclarativeSql.Dapper.SqlServerOperation.BulkInsert[T](IEnumerable`1 data)
       場所 DeclarativeSql.Dapper.IDbConnectionExtensions.BulkInsert[T](IDbConnection connection, IEnumerable`1 data, Nullable`1 timeout)
       場所 DeclarativeSqlTest.Program.Main(String[] args) 場所 c:\Users\XXX\Documents\Visual Studio 2013\Projects\DeclarativeSqlTest\DeclarativeSqlTest\Program.cs:行 22
       場所 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       場所 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       場所 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       場所 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       場所 System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

対応方法があればご教示お願いいたします。

**Comment by xin9le** [comment]
v0.2.5 で null 許可な対応を入れてみたのですが、それがマズいのかもしれません。
v0.2.4 で問題ないのであれば戻してご利用いただけると...！(ｽﾐﾏｾﾝ

**Comment by dndmfx** [comment]
お忙しいところ、早速の回答ありがとうございます。

> v0.2.5 で null 許可な対応を入れてみたのですが、それがマズいのかもしれません。

素人考えなので、見当違いかもしれませんが、#47の修正で追加された、
DataType = x.IsNullable ? Nullable.GetUnderlyingType(x.PropertyType) : x.PropertyType,
で、
Nullable.GetUnderlyingType(x.PropertyType)の戻り値nullが
DataTypeに設定されるのが原因なのかなと考えています。

> v0.2.4 で問題ないのであれば戻してご利用いただけると...！(ｽﾐﾏｾﾝ

バージョンを下げる方法で対応したいと思います。
できれば最新版を使いたいので、お時間のあるときに、
対応していただければ幸いです。

**Comment by xin9le** [comment]
以下のように属性を入れるとどうでしょうか？
```cs
public class Test
{
    [Key]  //--- 主キーであれば
    public int Id { get; set; }

    [Required]  //--- 列が null 許容でなければ
    public string Name { get; set; }
}
```
一度お試しいただけると幸いです。

**Comment by dndmfx** [comment]
> 以下のように属性を入れるとどうでしょうか？

属性をつけることで、v0.2.5、v0.2.6共にインサートに成功しました。
最新版が使える、属性をつける方法で対応したいと思います。
ご助言ありがとうございました。

またまた、素人考えですが、
```
DataType = x.IsNullable ? Nullable.GetUnderlyingType(x.PropertyType) : x.PropertyType,
AllowDBNull = x.IsNullable
```
は、
```
DataType = Nullable.GetUnderlyingType(x.PropertyType) != null ? Nullable.GetUnderlyingType(x.PropertyType) : x.PropertyType,
AllowDBNull = Nullable.GetUnderlyingType(x.PropertyType) != null ? true : x.PropertyType == typeof(string)  ? x.IsNullable : false
 ```
とすればうまくいくのかなと思いますが、どうでしょうか。
ご検討お願いいたします。

**Comment by dndmfx** [comment]
すみません。AllowDBNullはそのままでいいかもしれません。
