### ISSUE TITLE
Update single columns

### ISSUE THREAD

**Issue by deus82ex** [xin9le/DeclarativeSql#51]
Hi,

when I call an Update methode, not only the provided values are update but all columns. Is this a bug or am I doing something wrong?

    [Table("MEZ_BoxCall")]
    public class MEZ_BoxCall
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int BoxId { get; set; }
        public DateTime CallTimeStamp { get; set; }
        public DateTime? FinishTimeStamp { get; set; }
        public int? ForkLiftId { get; set; }
        public bool? Finished { get; set; }
        public int? Quantity { get; set; }
        public bool? Canceled { get; set; }
        public int? BoxCallTypeId { get; set; }
        [MaxLength(25)]
        public string MaterialNr { get; set; }
        [MaxLength]
        public string Caller { get; set; }
    }

connection.Update(new MEZ_BoxCall()
{
     Canceled = true
}, b => b.ID == boxCall.ID);

Regards Mario

**Comment by xin9le** [comment]
Thank you for using this library :)
Please try following.
```cs
connection.Update
(
    new MEZ_BoxCall(){ Canceled = true },
    x => x.ID == boxCall.ID,
    x => x.Canceled  // Plz add this.
);
```

If you wanna update multi column, try follows.
```cs
connection.Update
(
    new MEZ_BoxCall(){ Canceled = true,  Caller = "Mario" },
    x => x.ID == boxCall.ID,
    x => new { x.Canceled, x.Caller }
);
```
